---
- hosts: slave1
  become: yes
  name: Installing apache2 on dev
  tasks:
    - name: Install apache2
      apt: name=apache2 state=latest
    
- hosts: slave2
  become: yes
  name: Installing nginx
  tasks:
    - name: installing nginx
      apt: name=nginx state=latest
    - name: Running a script
      script: script.sh
